name: mon premier workflow

on:
  push:
    branches: ["master","develop"]

jobs:
  verifier-le-code:
    runs-on: ubuntu-latest

    steps:

      - name: telecharger les fichiers dans master
        uses: actions/checkout@v4
  
      - name: Afficher la liste des fichiers du projet
        run : ls -la
  
