name: CI Avancée - Filtrage par Paths

on:
  push:
    branches: ["master","develop","realese/**"]

    paths:
      - '**.html'
      - 'backend/**'
    paths-ignore:
      - 'readme.md'
      - 'testes/**'


  pull_request:
    branches: ["master","develop","realese/**"]
    type: [opened,synchronize]

    paths:
      - '**.html'
      - 'backend/**'
    paths-ignore:
      - 'readme.md'
      - 'testes/**'

jobs:

  verification-intelligente:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le code source
        uses: actions/checkout@v4

      - name: Lancer les vérifications sur le code
        run: |
         echo "=== LE ROBOT A FILTRÉ AVEC SUCCÈS ==="
         echo "Ce workflow ne s'est déclenché que parce qu'un fichier HTML ou du backend a été touché !"
         ls -la